language: php

php:
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer update --prefer-dist

jobs:
    include:
        - stage: test
          script: composer test
        - stage: static-analysis
          script: composer phpstan:analyze

notifications:
    email:
        recipients:
            - bbbara10@gmail.com
        on_success: never
        on_failure: always
